name: Create template ZIP

on:
    push:
        tags:
            - '*'
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        permissions:
            contents: write
        steps:
            - uses: actions/checkout@v4
            - name: Zip Template
              uses: TheDoctor0/zip-release@0.7.6
              with:
                  directory: './template'
                  type: 'zip'
                  filename: 'canvas-lord-${{ github.ref_name }}-with-template.zip'
                  command: 'mv -v ./engine/bin/* ./template/js'
            - uses: ncipollo/release-action@v1
              with:
                  artifacts: './engine/bin/canvas-lord-${{ github.ref_name }}-with-template.zip'
                  draft: true
                  token: ${{ secrets.GITHUB_TOKEN }}
